# Generated by Django 5.0.2 on 2024-02-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='path',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
