# Generated by Django 5.0.2 on 2024-02-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sals', '0003_remove_pelicula_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='path',
            field=models.CharField(default='the-grudge', max_length=300),
        ),
    ]
