# Generated by Django 5.0.2 on 2024-02-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sals', '0004_pelicula_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
