# Generated by Django 5.0.2 on 2024-02-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sals', '0005_alter_pelicula_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
