# Generated by Django 5.0.2 on 2024-02-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sals', '0007_alter_actor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula_actor',
            name='role',
        ),
    ]
