# Generated by Django 5.0.2 on 2024-02-19 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sals', '0008_remove_pelicula_actor_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('last_names', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula_Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_sals.keyword')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_sals.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_sals.keyword')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_sals.user')),
            ],
        ),
    ]
