# Generated by Django 4.2.10 on 2024-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sals', '0011_pelicula_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo',
            field=models.IntegerField(default=20212604, unique=True),
            preserve_default=False,
        ),
    ]
