# Generated by Django 4.2.10 on 2024-02-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sals', '0015_user_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(max_length=400),
        ),
    ]
